---
- name: Add ubercrawl user for management
  hosts: flame_workers

  tasks:
    # Stop the flame workers
    - name: Stop flame workers
      shell: "docker-compose -f 23fa-CIS5550-ubercrawl/aws/aws.frontend.yaml down"
      environment:
        FLAME_SERVER_HOST: 157.245.211.10
        FLAME_SERVER_PORT: 9000
        FLAME_WORKER_PORT: "{{ hostvars[inventory_hostname].port }}"

    # Start flame workers
    - name: Start Flame Workers
      shell: "docker-compose -f 23fa-CIS5550-ubercrawl/aws/aws.flame.worker.yaml up -d"
      environment:
        FLAME_SERVER_HOST: 157.245.211.10
        FLAME_SERVER_PORT: 9000
        FLAME_WORKER_PORT: "{{ hostvars[inventory_hostname].port }}"
