#!/usr/bin/env bash

set -o errexit;

JAVA_COMMAND="java -cp ubercrawl/lib/flame.jar:ubercrawl/lib/kvs.jar:ubercrawl/lib/jsoup-1.16.2.jar:ubercrawl/lib/webserver.jar:ubercrawl/lib/ubercrawl.jar";

function __clear_garbage() {
    echo "Clearing garbage...";
    #rm -rf "worker1/pt-crawl"
    #rm *.jar || echo "OK";
    echo "Done clearing, starting services now...";
}

function __ubercrawl_start_kvs() {
    echo "Starting cis5550.kvs.Coordinator";
    $JAVA_COMMAND cis5550.kvs.Coordinator 8000&
    sleep 1;
    echo "Starting: cis5550.kvs.Worker (1)";
    $JAVA_COMMAND cis5550.kvs.Worker 8001 worker1 localhost:8000 &
    echo "Starting: cis5550.kvs.Worker (1)";
    $JAVA_COMMAND cis5550.kvs.Worker 8002 worker2 localhost:8000 &
    echo "Starting: cis5550.kvs.Worker (3)";
    $JAVA_COMMAND cis5550.kvs.Worker 8003 worker3 localhost:8000 &
    sleep 1;
}

function __ubercrawl_start_flame() {
    echo "Starting: cis5550.flame.Coordinator";
    $JAVA_COMMAND cis5550.flame.Coordinator 9000 localhost:8000 &
    sleep 1;
    echo "Starting: cis5550.flame.Worker (1)";
    $JAVA_COMMAND cis5550.flame.Worker 9001 localhost:9000 &
    sleep 1;
    echo "Starting: cis5550.flame.Worker (2)";
    $JAVA_COMMAND cis5550.flame.Worker 9002 localhost:9000 &
    sleep 1;
}

function __ubercrawl_start_api() {
    echo "Starting: cis5550.api.SearchAPI";
    $JAVA_COMMAND cis5550.api.SearchAPI 8081 ubercrawl/static/MockData.json &
    sleep 1;
}

function start_api() {
    stop;
    build;
    __ubercrawl_start_api;
}



function __ubercrawl_stop() {
    echo "Stopping Services";

    # KVS Coordinator
    for KVS_PID in $(ps -ax | grep webserver | grep -v grep | awk '{print $1}');
    do
        echo "Stopping process id $KVS_PID";
        kill -9 $KVS_PID;
    done;
}


function __ubercrawl_restart() {
    __ubercrawl_stop;
    __ubercrawl_start_kvs;
    __ubercrawl_start_flame;
}



#
# Shortcuts
#
function start() {
    __ubercrawl_start_kvs;
    __ubercrawl_start_flame;
    __ubercrawl_start_api;
}

function stop() {
    __ubercrawl_stop;
}

function restart() {
    __ubercrawl_restart;
}

function build() {
    find ./ubercrawl/src -type f -name "*.java" -exec javac -classpath "./ubercrawl/lib/*:./src" -d ./ubercrawl/build '{}' +
    jar cvf ./ubercrawl.jar -C ./ubercrawl/build .;
}

function runCrawl() {
  $JAVA_COMMAND \
    cis5550.flame.FlameSubmit \
    localhost:9000 \
    ubercrawl/lib/ubercrawl.jar \
    cis5550.jobs.Crawler seed https://www.wikipedia.org;
}


function runIndexer() {
  $JAVA_COMMAND \
    cis5550.flame.FlameSubmit \
    localhost:9000 \
    ubercrawl/lib/ubercrawl.jar \
      cis5550.jobs.Indexer;
}

function runPageRank() {
  $JAVA_COMMAND \
    cis5550.flame.FlameSubmit \
    localhost:9000 \
    ubercrawl/lib/ubercrawl.jar \
      cis5550.jobs.PageRank;
}

echo "UberCrawl Java Services: $@" && $@;
