---
- name: Stop KVS Workers
  hosts: kvs_workers

  tasks:
    # Stop the kvs workers
    - name: Stop kvs workers
      shell: "docker-compose -f 23fa-CIS5550-ubercrawl/aws/aws.kvs.worker.yaml down"
      environment:
        KVS_SERVER_HOST: "{{ kvs_coordinator_ip }}"
        KVS_SERVER_PORT: "{{ kvs_coordinator_port }}"

    # Pull latest images
    - name: Pull repo
      shell: "/usr/bin/bash /home/ubercrawl/23fa-CIS5550-ubercrawl/gitpull.sh"

    # Pull latest images
    - name: Pull images
      shell: "/usr/bin/bash /home/ubercrawl/23fa-CIS5550-ubercrawl/dockerpull.sh"