---
- name: Start Flame Coordinators
  hosts: flame_coordinators

  tasks:
    # Start KVS Coordinator
    - name: Start Flame Coordinator
      shell: "docker-compose -f 23fa-CIS5550-ubercrawl/aws/aws.flame.coordinator.yaml up -d"
      environment:
        KVS_SERVER_HOST: "{{ kvs_coordinator_ip }}"
        KVS_SERVER_PORT: "{{ kvs_coordinator_port }}"
