version: '3.4'

services:
  flame_worker:
    image: ubercrawl_base:main
    ports:
      - "9001:9001"
    restart: always
    command: [ "java", "-cp", "/java/lib/*", "cis5550.flame.Worker", "9004", "${FLAME_SERVER_HOST}:${FLAME_SERVER_PORT}" ]
