version: '3.4'

services:
  kvs_worker:
    image: sergiogcx/ubercrawl_base:main
    ports:
      - "8001:8001"
    volumes:
      - ./data/worker:/app/worker
    restart: always
    command: [ "java", "-cp", "/java/lib/*", "cis5550.kvs.Worker", "8001", "worker", "${KVS_SERVER_HOST}:${KVS_SERVER_PORT}"]
