version: '3.4'

services:
  flame_coordinator:
    image: sergiogcx/ubercrawl_base:main
    ports:
      - "9000:9000"
    volumes:
      - ./data/flame_coordinator:/app/
    restart: always
    command: [ "java", "-cp", "/java/lib/*", "cis5550.flame.Coordinator", "9000", "${KVS_SERVER_HOST}:${KVS_SERVER_PORT}" ]
